/* author: jos.berkemeijer@planet.nl , Generated by AceHTML Freeware http://freeware.acehtml.com , Creation date: 05-14-2004 */
//<![CDATA[
// Version : activation on : onmouseover & onclick ; horizontal & vertical menu's tested in ie-6+ and netscape-7.1
// Do not remove this notice.  Copyright 2000-2004 by Mike Hall. See http://www.brainjar.com for terms of use.
function Browser() { var ua, s, i; this.isIE = false; this.isOP = false; this.isNS = false; this.version = null; ua = navigator.userAgent; s = "Opera"; if ((i = ua.indexOf(s)) >= 0) { this.isOP = true; this.version = parseFloat(ua.substr(i + s.length)); return;}
s = "Netscape6/"; if ((i = ua.indexOf(s)) >= 0) { this.isNS = true; this.version = parseFloat(ua.substr(i + s.length)); return;}
s = "Gecko"; if ((i = ua.indexOf(s)) >= 0) { this.isNS = true; this.version = 6.1; return;}
s = "MSIE"; if ((i = ua.indexOf(s))) { this.isIE = true; this.version = parseFloat(ua.substr(i + s.length)); return;}
}
var browser = new Browser(); var activeButton = null; function buttonClick(event, menuId) { var button; if (browser.isIE)
button = window.event.srcElement; else
button = event.currentTarget; button.blur(); if (button.menu == null) { button.menu = document.getElementById(menuId); if (button.menu.isInitialized == null)
menuInit(button.menu);}
if (button.onmouseout == null)
button.onmouseout = buttonOrMenuMouseout; if (button == activeButton)
return false; if (activeButton != null)
resetButton(activeButton); if (button != activeButton) { depressButton(button); activeButton = button;}
else
activeButton = null; return false;}
function buttonMouseover(event, menuId) { var button; if (activeButton == null) { buttonClick(event, menuId); return;}
if (browser.isIE)
button = window.event.srcElement; else
button = event.currentTarget; if (activeButton != null && activeButton != button)
buttonClick(event, menuId);}
function depressButton(button) { var x, y; button.className += " menuButtonActive"; if (button.onmouseout == null)
button.onmouseout = buttonOrMenuMouseout; if (button.menu.onmouseout == null)
button.menu.onmouseout = buttonOrMenuMouseout; x = getPageOffsetLeft(button)+(jbmenu_pos=="v")*(button.offsetWidth-1); y = getPageOffsetTop(button) +(jbmenu_pos=="h")*(button.offsetHeight-1); if (browser.isIE) { x += button.offsetParent.clientLeft; y += button.offsetParent.clientTop;}
button.menu.style.left = x + "px"; button.menu.style.top = y + "px"; button.menu.style.visibility = "visible";}
function resetButton(button) { removeClassName(button, "menuButtonActive"); if (button.menu != null) { closeSubMenu(button.menu); button.menu.style.visibility = "hidden";}
}
function menuMouseover(event) { var menu; if (browser.isIE)
menu = getContainerWith(window.event.srcElement, "DIV", "menu"); else
menu = event.currentTarget; if (menu.activeItem != null)
closeSubMenu(menu);}
function menuItemMouseover(event, menuId) { var item, menu, x, y; if (browser.isIE)
item = getContainerWith(window.event.srcElement, "A", "menuItem"); else
item = event.currentTarget; menu = getContainerWith(item, "DIV", "menu"); if (menu.activeItem != null)
closeSubMenu(menu); menu.activeItem = item; item.className += " menuItemHighlight"; if (item.subMenu == null) { item.subMenu = document.getElementById(menuId); if (item.subMenu.isInitialized == null)
menuInit(item.subMenu);}
menuhz(item.subMenu.style.zIndex)
item.subMenu.style.zIndex=menuhzindex+5
menuhz(item.subMenu.style.zIndex)
item.subMenu.style.zIndex=menuhzindex+5
if (item.subMenu.onmouseout == null)
item.subMenu.onmouseout = buttonOrMenuMouseout; x = getPageOffsetLeft(item) + item.offsetWidth; y = getPageOffsetTop(item); var maxX, maxY; if (browser.isIE) { maxX = Math.max(document.documentElement.scrollLeft, document.body.scrollLeft) + (document.documentElement.clientWidth != 0 ? document.documentElement.clientWidth : document.body.clientWidth); maxY = Math.max(document.documentElement.scrollTop, document.body.scrollTop) + (document.documentElement.clientHeight != 0 ? document.documentElement.clientHeight : document.body.clientHeight);}
if (browser.isOP) { maxX = document.documentElement.scrollLeft + window.innerWidth; maxY = document.documentElement.scrollTop + window.innerHeight;}
if (browser.isNS) { maxX = window.scrollX + window.innerWidth; maxY = window.scrollY + window.innerHeight;}
maxX -= item.subMenu.offsetWidth; maxY -= item.subMenu.offsetHeight; if (x > maxX)
x = Math.max(0, x - item.offsetWidth - item.subMenu.offsetWidth + (menu.offsetWidth - item.offsetWidth)); y = Math.max(0, Math.min(y, maxY)); item.subMenu.style.left = x + "px"; item.subMenu.style.top = y + "px"; item.subMenu.style.visibility = "visible"; if (browser.isIE)
window.event.cancelBubble = true; else
event.stopPropagation();}
function closeSubMenu(menu) { if (menu == null || menu.activeItem == null)
return; if (menu.activeItem.subMenu != null) { closeSubMenu(menu.activeItem.subMenu); menu.activeItem.subMenu.style.visibility = "hidden"; menu.activeItem.subMenu = null;}
removeClassName(menu.activeItem, "menuItemHighlight"); menu.activeItem = null;}
function buttonOrMenuMouseout(event) { var el; if (activeButton == null)
return; if (browser.isIE)
el = window.event.toElement; else if (event.relatedTarget != null)
el = (event.relatedTarget.tagName ? event.relatedTarget : event.relatedTarget.parentNode); if (getContainerWith(el, "DIV", "menu") == null) { resetButton(activeButton); activeButton = null;}
}
function menuInit(menu) { var itemList, spanList; var textEl, arrowEl; var itemWidth; var w, dw; var i, j; if (browser.isIE) { menu.style.lineHeight = "2.5ex"; spanList = menu.getElementsByTagName("SPAN"); for (i = 0; i < spanList.length; i++)
if (hasClassName(spanList[i], "menuItemArrow")) { spanList[i].style.fontFamily = "Webdings"; spanList[i].firstChild.nodeValue = "4";}
}
itemList = menu.getElementsByTagName("A"); if (itemList.length > 0)
itemWidth = itemList[0].offsetWidth; else
return; for (i = 0; i < itemList.length; i++) { spanList = itemList[i].getElementsByTagName("SPAN"); textEl = null; arrowEl = null; for (j = 0; j < spanList.length; j++) { if (hasClassName(spanList[j], "menuItemText"))
textEl = spanList[j]; if (hasClassName(spanList[j], "menuItemArrow"))
arrowEl = spanList[j];}
if (textEl != null && arrowEl != null) { textEl.style.paddingRight = (itemWidth - (textEl.offsetWidth + arrowEl.offsetWidth)) + "px"; if (browser.isOP | browser.isNS)
arrowEl.style.marginRight = "0px";}
}
if (browser.isIE) {var maxw=0; for (var i=0; i<itemList.length; i++){ maxw=Math.max(maxw,itemList[i].offsetWidth);}
for (var i=0; i<itemList.length; i++){ itemList[i].style.width = maxw+"px";}
}
menu.isInitialized = true;}
function getContainerWith(node, tagName, className) { while (node != null) { if (node.tagName != null && node.tagName == tagName &&
hasClassName(node, className))
return node; node = node.parentNode;}
return node;}
function hasClassName(el, name) { var i, list; list = el.className.split(" "); for (i = 0; i < list.length; i++)
if (list[i] == name)
return true; return false;}
function removeClassName(el, name) { var i, curList, newList; if (el.className == null)
return; newList = new Array(); curList = el.className.split(" "); for (i = 0; i < curList.length; i++)
if (curList[i] != name)
newList.push(curList[i]); el.className = newList.join(" ");}
function getPageOffsetLeft(el) { var x; x = el.offsetLeft; if (el.offsetParent != null)
x += getPageOffsetLeft(el.offsetParent); return x;}
function getPageOffsetTop(el) { var y; y = el.offsetTop; if (el.offsetParent != null)
y += getPageOffsetTop(el.offsetParent); return y;}
var menu_inss='<style type="text/css" > div.vertmenu * a.menuButton {white-space: nowrap;display:block}'
menu_inss+='div.menu{position: absolute; visibility: hidden;top:0px;z-index: 101;filter: progid:DXImageTransform.Microsoft.Shadow(direction=135,color=#808080,strength=3);}'
menu_inss+='</style>'
document.write (menu_inss)
function menuCreate(Mname,Morientation,Mms){ menu_gfs='font-size: 8pt;'
menu_gps='padding: 4px 2px 4px 2px;filter: progid:DXImageTransform.Microsoft.Shadow(direction=135,color=#808080,strength=3);'
menu_gbs='text-align: left;top: 0px;z-index: 100;cursor: default;position: relative; text-decoration: none; background-color: transparent;left: 0px;'
menu_gbs+='margin: 0px 0px 0px 1px;padding: 2px 2px 2px 6px;'
menu_gis='cursor: default; text-decoration: none;display: block;text-decoration: none;white-space: nowrap;color:#FF3300;padding: 3px 1em;'
menu_ghs='color: #FFFFFF;background-color: #4B0082;'
menu_rules=new Array;menu_rulenr=0;jbmenu_pos="h";menuButtonMaxWidth=0; menu_name=Mname; menuhzindex=1000; menu_ms=Mms;menuccc=0;menuddd=0
var ms='#'+Mname+'style'; var ss='#'+Mname; menu_sq=(menu_ms!='sub')
if (Morientation=='v'){menuhv='vertmenu';} else{menuhv='hormenu';}; if (menu_sq){cins='<div class="'+menuhv+'" id="'+Mname+'" style="position:absolute;visibility:hidden;"  onmousemove="jbmenu_pos=\''+Morientation+'\';"><div class="menuBar" id="'+Mname+'style"  onmousemove="jbmenu_pos=\''+Morientation+'\';">'}
else {cins='<div class="menu" id="'+Mname+'"  onmouseover="menuMouseover(event)">';}
menu_content =cins; menu_idstyle=ms; menu_gntxtstyle=ms+', '+ms+' a.menuButton, '+ms+' a.menuButton div.menu, '+ms+' a.menuButton div.menu a.menuItem' ; menu_gntxtstylec='{'; menu_barstyle=ms; menu_barstylec='{'+menu_gfs+menu_gps; menu_butstyle=ms+' a.menuButton'; menu_butstylec='{'+menu_gbs; menu_colhstyle=ms+' a.menuButtonActive, '+ms+' a.menuButtonActive:hover'; menu_colhstylec='{'; menu_itcolhstyle=ms+' * a.menuItem:hover , '+ms+' * a.menuItemHighlight'; menu_itcolhstylec='{'; menu_itcolnstyle=ms+' * div.menu, '+ms+' *  div.menu a.menuItem'; menu_itcolnstylec='{'; menu_substyle=ss; menu_substylec='{'+menu_gfs; menu_subnstyle=ss+' a'; menu_subnstylec='{'+menu_gis; menu_subostyle=ss+'  a.menuItem:hover,'+ss+'  a.menuItemHighlight'; menu_subostylec='{'+menu_ghs;}; function menuTextStyle(Msize,Mweight,Mfamily){; var mw="" , mf=""; if (Mfamily!=undefined){mf=';font-family:'+Mfamily+';'}; if (Mweight!=undefined){mw=';font-weight:'+Mweight+';'}; var st='font-size:'+Msize+';'+mw+mf; if (menu_ms!='sub'){menu_gntxtstylec+=st}
else{menu_subnstylec+=st;menu_substylec+=st;}
}; function menuColor(Mcolor,McolorOMO,Mbgcolor,MbgcolorOMO){; var cn='color:'+Mcolor+'; background-color:'+Mbgcolor+';' ; var co='color:'+McolorOMO+'; background-color:'+MbgcolorOMO+';' ; if (menu_sq){menu_gntxtstylec+=cn;menu_colhstylec+=co;}
else{menu_subnstylec+=cn;menu_substylec+=cn;menu_subostylec+=co;}
}; function menuWidth(Mwidth){; menu_width=Mwidth; menu_gntxtstylec+='width:'+Mwidth+';' ;}; function menuWidthIE(Mwidth){; if (document.all){menu_width=Mwidth; menu_gntxtstylec+='width:'+Mwidth+';' ;}
}; function menuBarWidth(Mwidth){; menuButtonMaxWidth=parseFloat(Mwidth)
}; function menuGeneralStyle(Mstyle){; if (menu_ms!='sub'){ menu_gntxtstylec+=Mstyle+';'}
else {menu_substylec+=Mstyle;}
}; function menuOnMousOverStyle(Mstyle){; if (menu_ms!='sub'){menu_colhstylec+=Mstyle+';'}
else {menu_subostylec+=Mstyle;};}; function menuBarStyle(Mstyle){; if (menu_ms!='sub'){menu_barstylec+=Mstyle+';'}
else {menu_substylec+=Mstyle;};}; function menuButtonStyle(Mstyle){; menu_butstylec+=Mstyle+';';}; function menuItemStyle(Mstyle){; menu_subnstylec+=Mstyle+';';}; function menuAddButton(Msubname,Mcontent){; var ins=""; if (Msubname!="none"){; ins=' onclick="return buttonClick(event, \''+Msubname+'\');" onmouseover="buttonMouseover(event, \''+Msubname+'\');" ';}; menu_content+='<a class="menuButton"  '+ins+'>'+Mcontent+'</a>'; menuButtonMaxWidth=Math.max(menuButtonMaxWidth,Mcontent.length);}; function menuAddButtonClick(Msubname,Mcontent){; var ins=""; if (Msubname!="none"){; ins=' onclick="return buttonClick(event, \''+Msubname+'\');"  ';}; menu_content+='<a class="menuButton"  '+ins+' title="Please click" >'+Mcontent+'</a>'; menuButtonMaxWidth=Math.max(menuButtonMaxWidth,Mcontent.length);}; function menuAddItem(Msubname,Mcontent){; var ins;if (Msubname!="none"){Mcontent+="&#160;"; ins='<a class="menuItem"  href="" onclick="return false;" onmouseover="menuItemMouseover(event, \''+Msubname+'\');" >'; ins+='<span class="menuItemText" >'+Mcontent+'</span><span class="menuItemArrow">&#9654;</span></a>'; menu_content+=ins;}
else{menu_content+='<a class="menuItem"  href="" onclick="return false;" >'+Mcontent+'</a>';};}; function menuAddItemClick(Msubname,Mcontent){; var ins;if (Msubname!="none"){Mcontent+="&#160;"; ins='<a class="menuItem"  href=""   onmouseover="if  (menuccc==1 & (\'hidden\'==document.getElementById(\''+Msubname+'\').style.visibility)){menuccc=0;};if (menuccc==1 ){menuItemMouseover(event, \''+Msubname+'\')};return false" onclick="menuccc=0;menuItemMouseover(event, \''+Msubname+'\');return false" onmouseout="if (menuccc==1 ){menuItemMouseover(event, \''+Msubname+'\')};return false" >'; ins+='<span class="menuItemText" >'+Mcontent+'</span><span class="menuItemArrow" onmouseover="menuccc=1;menuItemMouseover(event, \''+Msubname+'\')" onmouseout="menuccc=0">&#9654;</span></a>'; menu_content+=ins;}
else{menu_content+='<a class="menuItem"  href="" onclick="return false;">'+Mcontent+'</a>';};}; function menuAddLinkItem(Mcontent,Mlink,Mtitle){; var tit; if (Mtitle==undefined) { tit='' } else { tit='TITLE="'+Mtitle+'" ' }; var ins='<a class="menuItem"  href=""><span onclick="window.location=\''+Mlink+'\';return false;" '; ins+='onmouseover="this.style.cursor=\'hand\';"  '+tit+' >'+Mcontent+'</span></a>'; menu_content+=ins;}; function menuAddSeparator(Mstyle,Msigns){; if (Mstyle==undefined) {Mstyle='border: 1px inset #FFFFFF; margin: 1px 2px;'}; menu_content+='<div style="'+Mstyle+'"></div>';}; function menuAddAnything(Manything){; menu_content+=Manything;}; function menuEnd(){; menu_content+='</div>'; if (menu_ms!="sub"){menu_content+='</div>'}; if ((menuhv=="vertmenu") & (menu_ms!="sub") & document.all ){menu_barstylec+='width:'+menuButtonMaxWidth+'em ;' }; menu_gntxtstylec+="}";menu_barstylec+="}";menu_butstylec+="}"; menu_colhstylec+="}";menu_itcolhstylec+="}";menu_itcolnstylec+="}"; menu_substylec+="}";menu_subostylec+="}";menu_subnstylec+="}"; sts='<style>'+menu_gntxtstyle+menu_gntxtstylec; sts+=menu_barstyle+menu_barstylec; sts+=menu_butstyle+menu_butstylec; sts+=menu_colhstyle+menu_colhstylec; sts+=menu_itcolhstyle+menu_itcolhstylec; sts+=menu_itcolnstyle+menu_itcolnstylec; sts+='</style>'; if (menu_ms!="sub"){document.write(sts)}; sts='<style>'+menu_substyle+menu_substylec; sts+=menu_subostyle+menu_subostylec; sts+=menu_subnstyle+menu_subnstylec; sts+='</style>'; if (menu_ms=="sub"){document.write(sts)}; document.write(menu_content);}; function menuShow(Mname){; if (null==document.all){document.write('<div id="netscapefake" style="position:fixed;left:0px;top:127px;width:1006px;height:2000px;" align="left" valign="top" onmouseover="netscapefaker(\'hidden\')"></div>')}
var docs=document.getElementById(Mname); var vv=docs.className; if (vv=="hormenu"){ww="h"}else{ww="v"}; var wr='<span style="position:absolute" onmousemove="jbmenu_pos=\''+ww+'\';" onmouseout="netscapefaker(\'visible\')" onmouseover="jbmenu_pos=\''+ww+'\';"><div class="'+docs.className+'" id="'+Mname+'" onmouseover="jbmenu_pos=\''+ww+'\';" >'+docs.innerHTML+'</div></span>'; document.writeln (wr) ;}
function menuShowr(Mname,Mwidth){ ; menuShow(Mname); document.write ('<span style="margin-left:'+Mwidth+'"></span>');}; function menuShowa(Mname,Mleft,Mtop){; var docs=document.getElementById(Mname);vv=docs.className; var wr="<div style='position:absolute;left:"+Mleft+"px ;top:"+Mtop+"px ;' ><scr"+"ipt>menuShow('"+Mname+"')</script></div>"; document.write (wr) ;}; function netscapefaker(hv){; if (null==document.all){document.getElementById("netscapefake").style.visibility=hv};}; function menuhz(varz){; menuhzindex=Math.max(menuhzindex,varz);}; function menuArrowmargin(corr){; document.write("<style>div.menu a.menuItem span.menuItemArrow{margin-right: "+corr+";} </style>");}; function menuShadow(Fstrength,Fcolor,Fdirection){; if (Fdirection==undefined){Fdirection="135"; if (Fcolor==undefined){Fcolor="#808080";if (Fstrength==undefined){Fstrength="0"}}}; menuBarStyle("filter: progid:DXImageTransform.Microsoft.Shadow(direction="+Fdirection+",color="+Fcolor+",strength="+Fstrength+");");}; function menuPreStyle(Sname){ if (Sname=="Main-Ivory"){; menuTextStyle("10pt","normal","Verdana");menuColor("black","white","#c09070","#9999CC"); menuGeneralStyle("background-color: ivory; border:1px groove #708090;");menuBarStyle("padding:12px 0px 12px 0px; border: 3px outset #9999cc ;"); menuButtonStyle("margin:0px 15px 0px 15px;padding:5px 4px 5px 4px;font-weight:bold;text-decoration:underline;letter-spacing:2pt;");}
if (Sname=="Sub-Ivory"){menuColor("#B22222","#000000","ivory","#FAEBD7");menuBarStyle("margin-left:1px;padding:2px 2px 2px 2px;border: 2px outset #e0e0e0;"); menuItemStyle("padding: 2px 0px 2px 6px;")}
if (Sname=="Main-Windows98"){; menuTextStyle("9pt","normal","Tahoma");menuColor("#000000","#FFFFFF","#BFBFBF","#00007F"); menuGeneralStyle("border:2px ridge #FFFFFF;");menuBarStyle("padding:6px 2px 6px 2px; border: 1px outset #000000 ;"); menuButtonStyle("margin: -1px;padding:4px;font-weight:normal;letter-spacing:1pt;border: 2px outset #FFFFFF ;");}
if (Sname=="Sub-Windows98"){menuColor("#000000","#FFFFFF","#BFBFBF","#00007F");menuBarStyle("padding:3px 3px 3px 3px;border: 2px outset #e0e0e0;"); menuItemStyle("letter-spacing:1pt;padding: 3px 0px 3px 6px;")}
if (Sname=="Main-WindowsXP"){ menuTextStyle("10pt","normal","Verdana, Tahoma");menuColor("#000099","#F5F5F5","#f7f4e1","#0055ff"); menuGeneralStyle("font: bold 125% Verdana, Sans-serif;;border:1px ridge #0055ff;");menuBarStyle("background-color:#0055ff;padding:10px 4px 10px 4px; border: 0px normal #38a322 ;"); menuButtonStyle("background-color:#f7f4e1;margin: 5px;padding:5px 10px 5px 10px;letter-spacing:2pt;border: 2px inset #38a322 ;"); menuShadow(5,"#999966",135);}
if (Sname=="Sub-WindowsXP"){menuColor("#000099","#F5F5F5","#f7f4e1","#38a322");menuBarStyle("background-color:#0055ff;padding:2px 2px 2px 2px;border: 2px groove #38a322;"); menuItemStyle("margin-top:0px;margin:-1px 0px 0px 0px;padding: 2px 6px 2px 6px;border: 2px outset #f7f4e1");}
if (Sname=="Main-Transparent"){ ; menuTextStyle("10pt","normal","Arial");menuColor("#000000","#808080","transparent","#FFFACD"); menuGeneralStyle("font: bold 125% Arial, Sans-serif;;border:1px ridge #0055ff;");menuBarStyle("background-color:transparent;padding:14px 4px 12px 4px; border: 0px normal #38a322 ;"); menuButtonStyle("background-color:transparent;margin: 10px;padding:5px 10px 5px 10px;letter-spacing:2pt;border: 1px inset #4B0082 ;"); menuShadow(2,"#999966",60);}
if (Sname=="Sub-Transparent"){menuTextStyle("8pt","bold","Verdana");menuColor("#FFFFF0","#2F4F4F","transparent","#FFFACD");menuBarStyle("background-color:#123456;padding:2px 2px 2px 2px;border: 2px groove #38a322;"); menuItemStyle("background-color:transparent;margin-top:0px;margin:-1px 0px 0px 0px;letter-spacing:2pt;padding: 2px 4px 2px 6px;border: 2px outset #f7f4e1");}
if (Sname=="Main-Choco"){ ; menuTextStyle("9pt","bold","Arial,Tahoma"); menuColor("black","NAVY","#c09070","#EEE8AA"); menuGeneralStyle("background-color: #c09070;margin:0px;padding:0px 0px 0px 0px; "); menuBarStyle(" border-top: #e0b090;border-right: #906040;border-bottom: #906040;border-left: #e0b090;border-style:solid;border-width: 2px ;"); menuButtonStyle("letter-spacing:2pt;margin-left:4px;border: 1px solid #c09070;"); menuOnMousOverStyle("border-style:inset;");}
if (Sname=="Sub-Choco"){menuTextStyle("8pt","normal","Verdana,Tahoma");menuColor("black","NAVY","#c09070","#EEE8AA");menuBarStyle(" border-top: #e0b090;border-right: #906040;border-bottom: #906040;border-left: #e0b090;border-style:inset;border-width: 2px ;"); menuItemStyle("margin:-1px 0px 0px 0px;padding: 2px 0px 2px 6px;letter-spacing:1px;border: 3px inset #f7f4e1"); menuOnMousOverStyle("border: 3px inset #ADD8E6 ;");}
if (Sname=="Main-Chocreme"){ menuTextStyle("8pt","bold","Verdana"); menuColor("#ffffcc","#0033cc","#c09070","#D2691E"); menuGeneralStyle(" background-color: #c09070; border:1px groove #e0b090;"); menuBarStyle(" border-top: #e0b090;border-right: #906040;border-bottom: #906040;border-left: #e0b090;border-style:solid;border-width: 2px ;");}
if (Sname=="Sub-Chocreme"){ menuGeneralStyle('font-family: "MS Sans Serif", Arial, sans-serif; font-size: 8pt; font-style: normal;'); menuGeneralStyle('background-color: #e0e0e0;font-weight: normal; padding: 4px 2px 4px 2px;  text-align: left;'); menuColor("black","white","#e0e0e0","#a0a0a0");menuBarStyle("border: 2px outset #e0e0e0;"); menuColor("#B22222","#9400D3","#f5f5dc","#f5deb3");menuItemStyle("margin:-1px 0px 0px 0px;padding: 2px 0px 2px 6px;");}
if (Sname=="Sub-Chocreme-gray"){; menuGeneralStyle('font-family: "MS Sans Serif", Arial, sans-serif; font-size: 8pt; font-style: normal;'); menuGeneralStyle('background-color: #e0e0e0;font-weight: normal; padding: 4px 2px 4px 2px;  text-align: left;'); menuColor("black","white","#e0e0e0","#a0a0a0");menuBarStyle("border: 2px outset #e0e0e0;"); menuItemStyle("border: solid #C0C0C0 1px;margin: 1px 1px 1px 1px;padding: 2px 0px 2px 6px;");}
}
